const adoption = [
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog1.jpeg',
  	age: 1,
  	name: 'nana',
  	weight: '10kg',
  	length: '40cm',
  	height: '20cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '纯种拉布拉多，半岁，已经打疫苗',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog5.jpeg',
  	age: 2,
  	name: 'coco',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，金毛，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog6.jpeg',
  	age: 2,
  	name: 'lili',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog8.jpeg',
  	age: 3,
  	name: '可乐',
  	weight: '10kg',
  	length: '50cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog9.jpeg',
  	age: 3,
  	name: '雪碧',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog10.jpeg',
  	age: 3,
  	name: '半月',
  	weight: '10kg',
  	length: '80cm',
  	height: '40cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog12.jpeg',
  	age: 4,
  	name: '肚兜',
  	weight: '10kg',
  	length: '80cm',
  	height: '50cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/dog13.jpeg',
  	age: 2,
  	name: '土豆',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/cat2.jpeg',
  	age: 2,
  	name: 'jojo',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/cat3.jpeg',
  	age: 3,
  	name: '红糖',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/cat4.jpeg',
  	age: 1,
  	name: '挂面',
  	weight: '10kg',
  	length: '50cm',
  	height: '20cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/cat5.jpeg',
  	age: 2,
  	name: '甜瓜',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  },
  {
  	id: 1,
  	img: '/public/images/adoption/pets/cat6.jpeg',
  	age: 4,
  	name: '小明',
  	weight: '10kg',
  	length: '60cm',
  	height: '30cm',
  	species: 'dog',
  	category: '泰迪',	
  	title: '一岁半，不纯的萨摩，无偿转养',
  	location: '广东省深圳市福田区'
  }
]

export default adoption